### ISSUE TITLE
Select a license

### ISSUE THREAD

**Issue by stefanbirkner** [npathai/hamcrest-optional#20]
The library needs a license in order to be published on Maven Central. (See http://central.sonatype.org/pages/requirements.html). I suggest the MIT license, but feel free to choose a different one.

**Comment by npathai** [comment]
MIT license it is. Thanks for your support :+1:

**Comment by NersesAM** [comment]
@npathai Can you please add Licence information into the repo itself? Just like in most of github repos, in particular https://github.com/hamcrest/JavaHamcrest. This makes it easier for legal teams to approve the use of the library

**Comment by npathai** [comment]
@NersesAM Its done. I have added MIT license badge.
