### ISSUE TITLE
Rename hasValue() to hasOptionalValue().

### ISSUE THREAD

**Issue by garretwilson** [npathai/hamcrest-optional#24]
This is a needed library, but choosing the name `hasValue()` interferes with existing Hamcrest matchers. That is, I want to do static imports like this:

```java
import static org.junit.Assert.*;
import static org.hamcrest.Matchers.*;
import static com.github.npathai.hamcrestopt.OptionalMatchers.*;
```

But then I try to use an `Optional` matcher:

```java
assertThat(foo.getBar(), hasValue("foobar"));
```

Java tells me that the matcher `hasValue()` is ambiguous, pointing me to `Matchers.org.hamcrest.Matcher<java.util.Map<?, ? extends V>> hasValue(V value)`.

This could be alleviated by renaming `hasValue()` to `hasOptionalValue()`. Or noting that the `Optional` API speaks of `isPresent()`, you could use `isValuePresent()`.

I know this is merely cosmetic, but the following is ugly and inconvenient:

```java
assertThat(foo.getBar(), OptionalMatchers.hasValue("foobar"));
```

Thanks!

**Comment by npathai** [comment]
@garretwilson Sure I will release it with changes soon. Watch out for it. Thanks for pointing that.

**Comment by garretwilson** [comment]
I'm not sure of the status of this.

I also note that apparently you don't tag the releases; the "Releases" section has no information, so it's hard to tell when you release something new (which is why I have to bother you in asking, sorry).

**Comment by npathai** [comment]
@garretwilson Point noted. Releases have been tagged. 
Plus I have released new version 2.0.0 with the changes. Feel free to revert back. I will close this issue once the artifact is synced with maven central.
- [X] Update and push new version in central
- [X] Update readme and provide tags + release guides
- [x] Close issue once artifact syncs with maven central

**Comment by npathai** [comment]
@garretwilson Version 2.0.0 is now available via maven central

**Comment by garretwilson** [comment]
Thank you for being so helpful! We're already using the new version in several projects. All the best!

**Comment by npathai** [comment]
@garretwilson Awesome :+1: Cheers.
