### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by leozilla** [npathai/hamcrest-optional#25]
6 of 10 tests are failing after cloning the repo und running `mvn install`

Shouldnt you add the following to your junit test class when checking for `AssertionError`?
  ```
 @Before
   public void setup()
   {
      this.exception.handleAssertionErrors();
   }
```

[mvn_clean_install_log.txt](https://github.com/npathai/hamcrest-optional/files/954874/mvn_clean_install_log.txt)

**Comment by npathai** [comment]
Thanks @leozilla for raising this issue. I will look into this shortly.

**Comment by npathai** [comment]
@leozilla I appologize that I couldn't take time out. Have you figured out the problem yet. I am planning to pick it up this week. If you have figured the problem out feel free to raise a PR.

**Comment by npathai** [comment]
@leozilla They seem to work perfectly fine. Can you check again?
