### ISSUE TITLE
Update hamcrest to 2.2

### ISSUE THREAD

**Issue by saarmbruster** [npathai/hamcrest-optional#28]
The version of the hamcrest dependency is outdated. The latest version is 2.2. The packaging of hamcrest has been changed with 2.x (http://hamcrest.org/JavaHamcrest/distributables#upgrading-from-hamcrest-1x). I will open a PR to fix this.

**Comment by JoseRibeiro** [comment]
This update and a new version of hamcrest-optional would be greatly appreciated.
